### ISSUE TITLE
oxDNA to pdb conversion for looped structures

### ISSUE THREAD

**Issue by FionaSander** [lorenzo-rovigatti/tacoxDNA#24]
I am generating structures within oxDNA which are looped by connecting the 3' and 5' end nucleobases. 
When converting these to .pdb format using the oxDNA-pdb converter this connection seems to get lost due to the addition of hydrogen atoms at both ends. When using this pdb file as input for simulations outside of oxDNA the bond initially defined is ignored and the structure breaks. It might be useful to add an option for looped structures to keep the connection of start and end bases within pdb format.

**Comment by lorenzo-rovigatti** [comment]
The bug should have been fixed in 5d65932 (python3 branch, which will soon become the main branch). Let me know if it works!

**Comment by FionaSander** [comment]
Thanks for your quick answer, Lorenzo! I tested it on my system but it still disconnects the bond during conversion. I'm not using the is_circular option to connect the ends so that is probably the reason why your fix didn't work for me. The topology file I get after defining my system looks good however so could it be that there is a problem with the atoms added at 3' and 5' end during conversion?

**Comment by lorenzo-rovigatti** [comment]
Mhhhh I'm not sure I understand. If you are using a non-looping oxDNA topology then you'll get both 3" and 5" ends in the pdb. However, if you make the oxDNA topology looping (that is, if you connect the first and last nucleotides with a bond) then, with the last fix, your pdb shouldn't contain the 3" and 5" ends.
However, note that I might be missing something here, because I have no idea how looping strands are represented in the pdb. Do you have an example I can use to guide me?

**Comment by lorenzo-rovigatti** [comment]
I'm closing this issue for now since I think I fixed the bug. Feel free to reopen it if you think there are still issues!
