### ISSUE TITLE
oxDNA_PDB.py grooving

### ISSUE THREAD

**Issue by elija-feigl** [lorenzo-rovigatti/tacoxDNA#35]
It seems like the oxDNA to PDB conversion does not properly handle helical-grooving of the oxDNA2 model (img1).
most notable displayed as a low pass filtered map (img2).
grooving is properly displayed in oxView (img3).
(environment variable for oxDNA legacy utility is set to: OXDNA_GROOVE=1)

<img width="358" alt="oxDNA_PDB-grooving" src="https://user-images.githubusercontent.com/26200491/141972383-33b2e666-136e-442f-890b-f718fc88f44d.png">
<img width="357" alt="oxDNA_PDB-grooving2" src="https://user-images.githubusercontent.com/26200491/141972565-4eb4671b-63dd-48bd-a256-5b6a57043f0a.png">
<img width="248" alt="oxDNA_PDB-grooving3" src="https://user-images.githubusercontent.com/26200491/141972820-fb4a5b3b-addb-4af9-81f9-e5a68e81f1c4.png">

**Comment by lorenzo-rovigatti** [comment]
Thanks for the report.
I tried to solve this issue but I found out that the code knows nothing about grooving. In fact, the mapping between oxDNA and PDB nucleobases is done using only the bases' aromatic rings. The lack of correct grooving is due to this mapping, which is, from this point of view, subpar. Is this a big issue? Because I think that fixing it would require an extensive tinkering with the code (and probably some kind of fitting that should be done on a nucleotide-species basis).
